### ISSUE TITLE
Please check and confirm raspberry pi 4 support

### ISSUE THREAD

**Issue by Petrox** [sparkfun/PiServoHat_Py#1]
It is stated that the servo hat might or might not work with the Pi 4. 

Please clarify this in the docs and examples too.

**Comment by santaimpersonator** [comment]
I currently don't have the hardware available (working from home), but I'll add this to my to do list. I am 99% sure it'll work, the Pi 4 just wasn't available to test out any Qwiic Python packages on during the initial part of its release.

**Comment by santaimpersonator** [comment]
Works.
Updated product page and hookup guide.
Closing issue.
