### ISSUE TITLE
setPW / getPW / enable / disable channel method

### ISSUE THREAD

**Issue by Petrox** [sparkfun/PiServoHat_Py#3]
The board is capable of setting the clock, the duty cycle of a given channel.

The library is capable to set these measured in the range of a servo angle (eg 0-180).

It would be a nice improvement to define functions to set and get the PulseWidth of the current pattern. (Eg set_pulse_width(1500) should be the same as set_angle(90)).

also it would be nice to have a function to enable/disable the pwm for a given channel (0 pulse-width that is not the same as a 0 degree angle).

**Comment by santaimpersonator** [comment]
The pulse width need a frequency and time/width, which is no different than setting the frequency and duty cycle. Additionally, this is easily accomplished with the on/off methods of the PCA9685 package. I don't really see the benefit of this functionality for users. However, please feel free to submit a pull request or explain how why it is useful.

I don't think the PCA9685 allows users to "disable/enable" channels; at least not through I2C commands. However, feel free to enlighten me... if I am incorrect about that.
